<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>AdvanceDialogClass</name>
    <message>
        <source>Advance settings</source>
        <translation></translation>
    </message>
    <message>
        <source>检测属性</source>
        <translation></translation>
    </message>
    <message>
        <source>参考整体字符角度</source>
        <translation></translation>
    </message>
    <message>
        <source>测试字符</source>
        <translation></translation>
    </message>
    <message>
        <source>参考模组：</source>
        <translation></translation>
    </message>
    <message>
        <source>无参考</source>
        <translation></translation>
    </message>
    <message>
        <source>传入区域参考</source>
        <translation></translation>
    </message>
    <message>
        <source>识别整体区域</source>
        <translation></translation>
    </message>
    <message>
        <source>字符填充:</source>
        <translation></translation>
    </message>
    <message>
        <source> 自动模板扩大：</source>
        <translation></translation>
    </message>
    <message>
        <source>面积偏差：</source>
        <translation></translation>
    </message>
    <message>
        <source>检测多余和缺少</source>
        <translation></translation>
    </message>
    <message>
        <source>仅检测多余部分</source>
        <translation></translation>
    </message>
    <message>
        <source>仅检测缺少部分</source>
        <translation></translation>
    </message>
    <message>
        <source> 裂纹容忍值：     </source>
        <translation></translation>
    </message>
    <message>
        <source>字符1</source>
        <translation></translation>
    </message>
    <message>
        <source>比例因子：</source>
        <translation></translation>
    </message>
    <message>
        <source>字符阈值：</source>
        <translation></translation>
    </message>
    <message>
        <source>传入比例</source>
        <translation></translation>
    </message>
    <message>
        <source>启用OCR模板</source>
        <translation></translation>
    </message>
    <message>
        <source>多模板属性</source>
        <translation></translation>
    </message>
    <message>
        <source>0/180度</source>
        <translation></translation>
    </message>
    <message>
        <source>0/90/180/270度</source>
        <translation></translation>
    </message>
    <message>
        <source>模板组数</source>
        <translation></translation>
    </message>
    <message>
        <source>多字体</source>
        <translation></translation>
    </message>
    <message>
        <source>多图层</source>
        <translation></translation>
    </message>
    <message>
        <source>传入指定模板序号</source>
        <translation></translation>
    </message>
    <message>
        <source>极性多模板：</source>
        <translation></translation>
    </message>
    <message>
        <source>多模板：</source>
        <translation></translation>
    </message>
    <message>
        <source>清除模板</source>
        <translation></translation>
    </message>
    <message>
        <source>开批存模板路径</source>
        <translation></translation>
    </message>
    <message>
        <source>确认</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>OrientEditClass</name>
    <message>
        <source>Orient Edit</source>
        <translation></translation>
    </message>
    <message>
        <source>启用方向输出：</source>
        <translation></translation>
    </message>
    <message>
        <source>角度属性</source>
        <translation></translation>
    </message>
    <message>
        <source>None</source>
        <translation></translation>
    </message>
    <message>
        <source>out0</source>
        <translation></translation>
    </message>
    <message>
        <source>out1</source>
        <translation></translation>
    </message>
    <message>
        <source>out2</source>
        <translation></translation>
    </message>
    <message>
        <source>out3</source>
        <translation></translation>
    </message>
    <message>
        <source>out4</source>
        <translation></translation>
    </message>
    <message>
        <source>out5</source>
        <translation></translation>
    </message>
    <message>
        <source>out6</source>
        <translation></translation>
    </message>
    <message>
        <source>out7</source>
        <translation></translation>
    </message>
    <message>
        <source>out8</source>
        <translation></translation>
    </message>
    <message>
        <source>out9</source>
        <translation></translation>
    </message>
    <message>
        <source>out10</source>
        <translation></translation>
    </message>
    <message>
        <source>out11</source>
        <translation></translation>
    </message>
    <message>
        <source>out12</source>
        <translation></translation>
    </message>
    <message>
        <source>out13</source>
        <translation></translation>
    </message>
    <message>
        <source>out14</source>
        <translation></translation>
    </message>
    <message>
        <source>out15</source>
        <translation></translation>
    </message>
    <message>
        <source>out16</source>
        <translation></translation>
    </message>
    <message>
        <source>out17</source>
        <translation></translation>
    </message>
    <message>
        <source>out18</source>
        <translation></translation>
    </message>
    <message>
        <source>out19</source>
        <translation></translation>
    </message>
    <message>
        <source>out20</source>
        <translation></translation>
    </message>
    <message>
        <source>out21</source>
        <translation></translation>
    </message>
    <message>
        <source>out22</source>
        <translation></translation>
    </message>
    <message>
        <source>out23</source>
        <translation></translation>
    </message>
    <message>
        <source>out24</source>
        <translation></translation>
    </message>
    <message>
        <source>out25</source>
        <translation></translation>
    </message>
    <message>
        <source>out26</source>
        <translation></translation>
    </message>
    <message>
        <source>out27</source>
        <translation></translation>
    </message>
    <message>
        <source>out28</source>
        <translation></translation>
    </message>
    <message>
        <source>out29</source>
        <translation></translation>
    </message>
    <message>
        <source>out30</source>
        <translation></translation>
    </message>
    <message>
        <source>out31</source>
        <translation></translation>
    </message>
    <message>
        <source>使用默认信号输出</source>
        <translation></translation>
    </message>
    <message>
        <source>两方向</source>
        <translation></translation>
    </message>
    <message>
        <source>四方向</source>
        <translation></translation>
    </message>
    <message>
        <source>反向</source>
        <translation></translation>
    </message>
    <message>
        <source>左/Pin-1：</source>
        <translation></translation>
    </message>
    <message>
        <source>右/Pin-2：</source>
        <translation></translation>
    </message>
    <message>
        <source>显示角度</source>
        <translation></translation>
    </message>
    <message>
        <source>信号编辑</source>
        <translation></translation>
    </message>
    <message>
        <source>90度</source>
        <translation></translation>
    </message>
    <message>
        <source>180度</source>
        <translation></translation>
    </message>
    <message>
        <source>270度</source>
        <translation></translation>
    </message>
    <message>
        <source>0度</source>
        <translation></translation>
    </message>
    <message>
        <source>使用默认信号编辑</source>
        <translation></translation>
    </message>
    <message>
        <source>确认</source>
        <translation></translation>
    </message>
    <message>
        <source>取消</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <source>char region out of search Region! please reset template.</source>
        <translation></translation>
    </message>
    <message>
        <source> auto template by OCR failed! </source>
        <translation>根据OCR自动做模板失败！</translation>
    </message>
    <message>
        <source> no template is ready,please set template!</source>
        <translation>没有可用模板，请设置模板！</translation>
    </message>
    <message>
        <source>character&apos;s number is zero</source>
        <translation>字符数目为0</translation>
    </message>
    <message>
        <source> different templates&apos; character&apos;s numbers varies when using multiple fonts</source>
        <translation>当使用多字体模式时，不同模板的字符数目不应不同</translation>
    </message>
    <message>
        <source> the region of characters of template %1 is beyond Global character region</source>
        <translation>模板%1的单字符区域超出整体模板区域，请重新设置模板</translation>
    </message>
    <message>
        <source>the set of Multi-directional templates when using the function of outputting direction is wrong,please check it</source>
        <translation>在使用角度输出属性时未启用极性多模板，请检查相应设置</translation>
    </message>
    <message>
        <source>Global character region match fail</source>
        <translation>全局字符区域匹配失败</translation>
    </message>
    <message>
        <source>match score=%1</source>
        <translation>匹配得分=%1</translation>
    </message>
    <message>
        <source>Global character region match score=%1</source>
        <translation>全局字符区域匹配得分=%1</translation>
    </message>
    <message>
        <source>matched layer is template %1</source>
        <translation>匹配到的图层是模板%1</translation>
    </message>
    <message>
        <source>char[%1]&apos; match fail,</source>
        <translation>字符[%1]匹配失败</translation>
    </message>
    <message>
        <source> score = %1(%2)</source>
        <translation>分数=%1（%2）</translation>
    </message>
    <message>
        <source>,angle =%1(%2)</source>
        <translation>,angle =%1(%2)</translation>
    </message>
    <message>
        <source>char[%1]&apos;s score = %2(%3)</source>
        <translation>字符[%1]分数= %2(%3)</translation>
    </message>
    <message>
        <source>,offset =%1(%2)</source>
        <translation>,偏移值=%1(%2)</translation>
    </message>
    <message>
        <source>Mark shift X: %1(%2,%3)</source>
        <translation>字符边距X：%1(%2,%3)</translation>
    </message>
    <message>
        <source>Mark shift Y: %1(%2,%3)</source>
        <translation>字符边距Y：%1(%2,%3)</translation>
    </message>
    <message>
        <source>area difference:%1(%2)</source>
        <translation>面积偏差：%1(%2)(%)</translation>
    </message>
    <message>
        <source>max char crack :%1(%2)</source>
        <translation>最大残缺: %1 (%2)</translation>
    </message>
    <message>
        <source>max char excess :%1(%2)(%)</source>
        <translation>最大多余: %1 (%2)</translation>
    </message>
    <message>
        <source>match failed</source>
        <translation>匹配失败</translation>
    </message>
    <message>
        <source>match success</source>
        <translation>匹配成功</translation>
    </message>
</context>
<context>
    <name>mark1Wdg</name>
    <message>
        <source>mark1Wdg</source>
        <translation></translation>
    </message>
    <message>
        <source>查看模板</source>
        <translation></translation>
    </message>
    <message>
        <source>模板一</source>
        <translation></translation>
    </message>
    <message>
        <source>模板二</source>
        <translation></translation>
    </message>
    <message>
        <source>模板三</source>
        <translation></translation>
    </message>
    <message>
        <source>模板四</source>
        <translation></translation>
    </message>
    <message>
        <source>已设此模板</source>
        <translation></translation>
    </message>
    <message>
        <source>方向属性</source>
        <translation></translation>
    </message>
    <message>
        <source>学习模板</source>
        <translation></translation>
    </message>
    <message>
        <source>白色印字:</source>
        <translation></translation>
    </message>
    <message>
        <source>选取字符区域</source>
        <translation></translation>
    </message>
    <message>
        <source>自动分割:</source>
        <translation></translation>
    </message>
    <message>
        <source>选取模板</source>
        <translation></translation>
    </message>
    <message>
        <source>确认选取</source>
        <translation></translation>
    </message>
    <message>
        <source>取消选取</source>
        <translation></translation>
    </message>
    <message>
        <source>自动模板</source>
        <translation></translation>
    </message>
    <message>
        <source>字符数目：</source>
        <translation></translation>
    </message>
    <message>
        <source>设入</source>
        <translation></translation>
    </message>
    <message>
        <source>检测属性</source>
        <translation></translation>
    </message>
    <message>
        <source>印字偏移：</source>
        <translation></translation>
    </message>
    <message>
        <source>搜寻角度：</source>
        <translation></translation>
    </message>
    <message>
        <source>高级检测设置</source>
        <translation></translation>
    </message>
    <message>
        <source>误差范围</source>
        <translation></translation>
    </message>
    <message>
        <source>面积偏差：</source>
        <translation></translation>
    </message>
    <message>
        <source>接受值：</source>
        <translation></translation>
    </message>
    <message>
        <source>角度：</source>
        <translation></translation>
    </message>
    <message>
        <source>%</source>
        <translation></translation>
    </message>
    <message>
        <source>边距X向：</source>
        <translation></translation>
    </message>
    <message>
        <source>边距Y向：</source>
        <translation></translation>
    </message>
    <message>
        <source>偏移距离：</source>
        <translation></translation>
    </message>
    <message>
        <source>字符多余：</source>
        <translation></translation>
    </message>
    <message>
        <source>字符残缺：</source>
        <translation></translation>
    </message>
    <message>
        <source>Char%1</source>
        <translation>字符%1</translation>
    </message>
    <message>
        <source>template%1</source>
        <translation>模板%1</translation>
    </message>
    <message>
        <source>Advanced</source>
        <translation>高级设置</translation>
    </message>
    <message>
        <source>template set</source>
        <translation>已设此模板</translation>
    </message>
    <message>
        <source>template unset</source>
        <translation>未设此模板</translation>
    </message>
    <message>
        <source>Warning</source>
        <translation>警告</translation>
    </message>
    <message>
        <source>no image for setting template!</source>
        <translation>没有图片用于设置模板！</translation>
    </message>
    <message>
        <source>char region out of search Region! please reset template.</source>
        <translation>字符区域超过搜索区域！请重设模板.</translation>
    </message>
    <message>
        <source>Hint</source>
        <translation>提示</translation>
    </message>
    <message>
        <source>The current template is not available, please set the template first! </source>
        <translation>当前组别模板不可用，请先设置模板！</translation>
    </message>
    <message>
        <source>warning</source>
        <translation>警告</translation>
    </message>
    <message>
        <source>Are you sure to delete all templates for the current group?</source>
        <translation>确定删除当前组别的所有模板?</translation>
    </message>
    <message>
        <source>Only allowed to set the number of characters at template 1!</source>
        <translation>只允许在模板一设置字符数目！</translation>
    </message>
    <message>
        <source>exit test</source>
        <translation>退出测试</translation>
    </message>
    <message>
        <source>test char</source>
        <translation>测试字符</translation>
    </message>
    <message>
        <source>Check</source>
        <translation>启用</translation>
    </message>
    <message>
        <source>unCheck</source>
        <translation>不启用</translation>
    </message>
    <message>
        <source> change from %1 to %2</source>
        <translation>从%1改变为%2</translation>
    </message>
    <message>
        <source> min value change from %1 to %2</source>
        <translation>最小值从%1变化到%2</translation>
    </message>
    <message>
        <source> max value change from %1 to %2</source>
        <translation>最大值从%1变化到%2</translation>
    </message>
    <message>
        <source>In Multiple Fonts Model Now.The number of characters doesn&apos;t match the number of characters in the template 1.Please reset!</source>
        <translation>当前是多字体模式。当前模板字符数目不匹配模板一的字符数目，请重新设置！</translation>
    </message>
</context>
<context>
    <name>showWidgetClass</name>
    <message>
        <source>Template</source>
        <translation></translation>
    </message>
    <message>
        <source>退出</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>thresholdWidget</name>
    <message>
        <source>Threshold Dialog</source>
        <translation></translation>
    </message>
    <message>
        <source>印字</source>
        <translation></translation>
    </message>
    <message>
        <source>最小面积值：</source>
        <translation></translation>
    </message>
    <message>
        <source>最小孔洞：</source>
        <translation></translation>
    </message>
    <message>
        <source>裂纹容忍值：</source>
        <translation></translation>
    </message>
    <message>
        <source>字符方向</source>
        <translation></translation>
    </message>
    <message>
        <source>左右</source>
        <translation></translation>
    </message>
    <message>
        <source>上下</source>
        <translation></translation>
    </message>
    <message>
        <source>字符间隔：</source>
        <translation></translation>
    </message>
    <message>
        <source>字符1</source>
        <translation></translation>
    </message>
    <message>
        <source>印字数目：</source>
        <translation></translation>
    </message>
    <message>
        <source>阈值处理</source>
        <translation></translation>
    </message>
    <message>
        <source>确定</source>
        <translation></translation>
    </message>
    <message>
        <source>取消</source>
        <translation></translation>
    </message>
    <message>
        <source>%1</source>
        <translation></translation>
    </message>
</context>
</TS>
