<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>QObject</name>
    <message>
        <source>direction of 0</source>
        <translation>0°方向</translation>
    </message>
    <message>
        <source>direction of %1</source>
        <translation>%1°方向</translation>
    </message>
    <message>
        <source>Empty image</source>
        <translation>无图片传入！</translation>
    </message>
    <message>
        <source>Template unset!</source>
        <translation>模板未设置！</translation>
    </message>
    <message>
        <source>detected failed</source>
        <translation>识别失败</translation>
    </message>
    <message>
        <source>region%1: </source>
        <translation>区域%1： </translation>
    </message>
    <message>
        <source>detection result:%1</source>
        <translation>识别结果：%1</translation>
    </message>
    <message>
        <source>accepted value: </source>
        <translation>接受值： </translation>
    </message>
    <message>
        <source>relative angle: </source>
        <translation>相对角度： </translation>
    </message>
    <message>
        <source>detected succesfully</source>
        <translation>识别成功</translation>
    </message>
    <message>
        <source>matching angle failed </source>
        <translation>一致性检测失败 </translation>
    </message>
</context>
<context>
    <name>nccMatch_fourDirWdg</name>
    <message>
        <source>nccMatch_fourDirWdg</source>
        <translation></translation>
    </message>
    <message>
        <source>选取模版</source>
        <translation></translation>
    </message>
    <message>
        <source>确认选取</source>
        <translation></translation>
    </message>
    <message>
        <source>取消选取</source>
        <translation></translation>
    </message>
    <message>
        <source>显示模板</source>
        <translation></translation>
    </message>
    <message>
        <source>  0°</source>
        <translation></translation>
    </message>
    <message>
        <source>  90°</source>
        <translation></translation>
    </message>
    <message>
        <source>  180°</source>
        <translation></translation>
    </message>
    <message>
        <source>  270°</source>
        <translation></translation>
    </message>
    <message>
        <source>信号编辑</source>
        <translation></translation>
    </message>
    <message>
        <source>角度属性</source>
        <translation></translation>
    </message>
    <message>
        <source>out0</source>
        <translation></translation>
    </message>
    <message>
        <source>out1</source>
        <translation></translation>
    </message>
    <message>
        <source>out2</source>
        <translation></translation>
    </message>
    <message>
        <source>out3</source>
        <translation></translation>
    </message>
    <message>
        <source>out4</source>
        <translation></translation>
    </message>
    <message>
        <source>out5</source>
        <translation></translation>
    </message>
    <message>
        <source>out6</source>
        <translation></translation>
    </message>
    <message>
        <source>out7</source>
        <translation></translation>
    </message>
    <message>
        <source>out8</source>
        <translation></translation>
    </message>
    <message>
        <source>out9</source>
        <translation></translation>
    </message>
    <message>
        <source>out10</source>
        <translation></translation>
    </message>
    <message>
        <source>out11</source>
        <translation></translation>
    </message>
    <message>
        <source>out12</source>
        <translation></translation>
    </message>
    <message>
        <source>out13</source>
        <translation></translation>
    </message>
    <message>
        <source>out14</source>
        <translation></translation>
    </message>
    <message>
        <source>out15</source>
        <translation></translation>
    </message>
    <message>
        <source>out16</source>
        <translation></translation>
    </message>
    <message>
        <source>out17</source>
        <translation></translation>
    </message>
    <message>
        <source>out18</source>
        <translation></translation>
    </message>
    <message>
        <source>out19</source>
        <translation></translation>
    </message>
    <message>
        <source>out20</source>
        <translation></translation>
    </message>
    <message>
        <source>out21</source>
        <translation></translation>
    </message>
    <message>
        <source>out22</source>
        <translation></translation>
    </message>
    <message>
        <source>out23</source>
        <translation></translation>
    </message>
    <message>
        <source>out24</source>
        <translation></translation>
    </message>
    <message>
        <source>out25</source>
        <translation></translation>
    </message>
    <message>
        <source>out26</source>
        <translation></translation>
    </message>
    <message>
        <source>out27</source>
        <translation></translation>
    </message>
    <message>
        <source>out28</source>
        <translation></translation>
    </message>
    <message>
        <source>out29</source>
        <translation></translation>
    </message>
    <message>
        <source>out30</source>
        <translation></translation>
    </message>
    <message>
        <source>out31</source>
        <translation></translation>
    </message>
    <message>
        <source>两方向</source>
        <translation></translation>
    </message>
    <message>
        <source>四方向</source>
        <translation></translation>
    </message>
    <message>
        <source>默认输出</source>
        <translation></translation>
    </message>
    <message>
        <source>启用</source>
        <translation></translation>
    </message>
    <message>
        <source>左/Pin-1：</source>
        <translation></translation>
    </message>
    <message>
        <source>右/Pin-2：</source>
        <translation></translation>
    </message>
    <message>
        <source>方向输出：</source>
        <translation></translation>
    </message>
    <message>
        <source>起始角度</source>
        <translation></translation>
    </message>
    <message>
        <source>90度</source>
        <translation></translation>
    </message>
    <message>
        <source>180度</source>
        <translation></translation>
    </message>
    <message>
        <source>270度</source>
        <translation></translation>
    </message>
    <message>
        <source>0度</source>
        <translation></translation>
    </message>
    <message>
        <source>使用默认信号编辑</source>
        <translation></translation>
    </message>
    <message>
        <source>使用参考区域: </source>
        <translation></translation>
    </message>
    <message>
        <source>左右镜像</source>
        <translation></translation>
    </message>
    <message>
        <source>上下镜像</source>
        <translation></translation>
    </message>
    <message>
        <source>镜像型两方向</source>
        <translation></translation>
    </message>
    <message>
        <source>搜寻角度：</source>
        <translation></translation>
    </message>
    <message>
        <source>相似度：</source>
        <translation></translation>
    </message>
    <message>
        <source>误差范围</source>
        <translation></translation>
    </message>
    <message>
        <source>接受值：</source>
        <translation></translation>
    </message>
    <message>
        <source>相对角度：</source>
        <translation></translation>
    </message>
    <message>
        <source>启用一致性判断：</source>
        <translation></translation>
    </message>
    <message>
        <source>传出区域</source>
        <translation></translation>
    </message>
    <message>
        <source>启用传出区域</source>
        <translation></translation>
    </message>
    <message>
        <source>显示传出区域</source>
        <translation></translation>
    </message>
    <message>
        <source>填充区域</source>
        <translation></translation>
    </message>
    <message>
        <source>选取传出模版</source>
        <translation></translation>
    </message>
    <message>
        <source>目标区域：</source>
        <translation></translation>
    </message>
    <message>
        <source>排除区域：</source>
        <translation></translation>
    </message>
    <message>
        <source>面积：</source>
        <translation></translation>
    </message>
    <message>
        <source>阈值测试</source>
        <translation></translation>
    </message>
    <message>
        <source>Warning</source>
        <translation>警告</translation>
    </message>
    <message>
        <source>The template of outArea is unset!</source>
        <translation>传出区域模板未设置！</translation>
    </message>
    <message>
        <source>temp</source>
        <translation>模板</translation>
    </message>
    <message>
        <source>ROI</source>
        <translation></translation>
    </message>
    <message>
        <source>exit Edit</source>
        <translation>退出编辑</translation>
    </message>
    <message>
        <source>Edit Signal</source>
        <translation>编辑信号</translation>
    </message>
    <message>
        <source> change from %1 to %2</source>
        <translation>从%1改变为%2</translation>
    </message>
    <message>
        <source> Check</source>
        <translation>启用</translation>
    </message>
    <message>
        <source> unCheck</source>
        <translation>不启用</translation>
    </message>
    <message>
        <source> min val </source>
        <translation>最小值</translation>
    </message>
    <message>
        <source> max val </source>
        <translation>最大值</translation>
    </message>
</context>
</TS>
