<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>QObject</name>
    <message>
        <source>Empty image!</source>
        <translation>无图片传入！</translation>
    </message>
    <message>
        <source>Input matrix&apos;s size != 6!</source>
        <translation>输入矩阵大小不等于6！</translation>
    </message>
    <message>
        <source>left</source>
        <translation>左</translation>
    </message>
    <message>
        <source>right</source>
        <translation>右</translation>
    </message>
</context>
<context>
    <name>polarWdg</name>
    <message>
        <source>polarWdg</source>
        <translation></translation>
    </message>
    <message>
        <source>用于快速定位到两边的直线选框</source>
        <translation></translation>
    </message>
    <message>
        <source>选辅助框</source>
        <translation></translation>
    </message>
    <message>
        <source>确定框</source>
        <translation></translation>
    </message>
    <message>
        <source>取消框</source>
        <translation></translation>
    </message>
    <message>
        <source>选直线</source>
        <translation></translation>
    </message>
    <message>
        <source>确定</source>
        <translation></translation>
    </message>
    <message>
        <source>取消</source>
        <translation></translation>
    </message>
    <message>
        <source>旋转矩阵参考</source>
        <translation></translation>
    </message>
    <message>
        <source>测后显示</source>
        <translation></translation>
    </message>
    <message>
        <source>选择直线</source>
        <translation></translation>
    </message>
    <message>
        <source>左一</source>
        <translation></translation>
    </message>
    <message>
        <source>左二</source>
        <translation></translation>
    </message>
    <message>
        <source>右一</source>
        <translation></translation>
    </message>
    <message>
        <source>右二</source>
        <translation></translation>
    </message>
    <message>
        <source>所有边运用左一参数</source>
        <translation></translation>
    </message>
    <message>
        <source>线属性</source>
        <translation></translation>
    </message>
    <message>
        <source>对比度</source>
        <translation></translation>
    </message>
    <message>
        <source>毛边</source>
        <translation></translation>
    </message>
    <message>
        <source>角度范围(度)</source>
        <translation></translation>
    </message>
    <message>
        <source>最大迭代次数</source>
        <translation></translation>
    </message>
    <message>
        <source>双向</source>
        <translation></translation>
    </message>
    <message>
        <source>黑到白</source>
        <translation></translation>
    </message>
    <message>
        <source>白到黑</source>
        <translation></translation>
    </message>
    <message>
        <source>最大对比</source>
        <translation></translation>
    </message>
    <message>
        <source>第一条</source>
        <translation></translation>
    </message>
    <message>
        <source>排除距离</source>
        <translation></translation>
    </message>
    <message>
        <source>更多参数</source>
        <translation></translation>
    </message>
    <message>
        <source>选择标准</source>
        <translation></translation>
    </message>
    <message>
        <source>0度标准：</source>
        <translation></translation>
    </message>
    <message>
        <source>左&lt;右</source>
        <translation></translation>
    </message>
    <message>
        <source>左&gt;右</source>
        <translation></translation>
    </message>
    <message>
        <source>大角范围</source>
        <translation></translation>
    </message>
    <message>
        <source>小角范围</source>
        <translation></translation>
    </message>
    <message>
        <source>角度属性</source>
        <translation></translation>
    </message>
    <message>
        <source>默认输出</source>
        <translation></translation>
    </message>
    <message>
        <source>information</source>
        <translation>提示</translation>
    </message>
    <message>
        <source>Whether to apply the base line parameters to all regions?</source>
        <translation>是否将左1参数运用于其他区域？</translation>
    </message>
    <message>
        <source>left</source>
        <translation>左</translation>
    </message>
    <message>
        <source>right</source>
        <translation>右</translation>
    </message>
    <message>
        <source>left 1</source>
        <translation>左1</translation>
    </message>
    <message>
        <source>left 2</source>
        <translation>左2</translation>
    </message>
    <message>
        <source>right 1</source>
        <translation>右1</translation>
    </message>
    <message>
        <source>right 2</source>
        <translation>右2</translation>
    </message>
</context>
</TS>
