<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>QObject</name>
    <message>
        <source>Empty image!</source>
        <translation>无图片传入！</translation>
    </message>
    <message>
        <source>Module invalid!</source>
        <translation>模块未启用！</translation>
    </message>
    <message>
        <source>Succeed!</source>
        <translation>处理成功！</translation>
    </message>
</context>
<context>
    <name>imageSegment_preWdg</name>
    <message>
        <source>imageSegment_preWdg</source>
        <translation></translation>
    </message>
    <message>
        <source>属性</source>
        <translation></translation>
    </message>
    <message>
        <source>模块开启：</source>
        <translation></translation>
    </message>
    <message>
        <source>选择区域</source>
        <translation></translation>
    </message>
    <message>
        <source>整幅图像：</source>
        <translation></translation>
    </message>
    <message>
        <source>ROI-1</source>
        <translation></translation>
    </message>
    <message>
        <source>Roi数目：</source>
        <translation></translation>
    </message>
    <message>
        <source>测试模式</source>
        <translation></translation>
    </message>
    <message>
        <source>二值化方案</source>
        <translation></translation>
    </message>
    <message>
        <source>阈值分割</source>
        <translation></translation>
    </message>
    <message>
        <source>区域生长</source>
        <translation></translation>
    </message>
    <message>
        <source>最小阈值</source>
        <translation></translation>
    </message>
    <message>
        <source>最大阈值</source>
        <translation></translation>
    </message>
    <message>
        <source>面积：</source>
        <translation></translation>
    </message>
    <message>
        <source>min：</source>
        <translation>最小值：</translation>
    </message>
    <message>
        <source>max：</source>
        <translation>最大值：</translation>
    </message>
    <message>
        <source>x:</source>
        <translation></translation>
    </message>
    <message>
        <source>y:</source>
        <translation></translation>
    </message>
    <message>
        <source>灰度差距</source>
        <translation></translation>
    </message>
    <message>
        <source>最小面积</source>
        <translation></translation>
    </message>
    <message>
        <source>列距离</source>
        <translation></translation>
    </message>
    <message>
        <source>行距离</source>
        <translation></translation>
    </message>
    <message>
        <source>以ROI中心为种子点</source>
        <translation></translation>
    </message>
    <message>
        <source>采用平均值生长</source>
        <translation></translation>
    </message>
    <message>
        <source>设置种子点</source>
        <translation></translation>
    </message>
    <message>
        <source>不使用种子点</source>
        <translation></translation>
    </message>
    <message>
        <source>处理算法</source>
        <translation></translation>
    </message>
    <message>
        <source>种类：</source>
        <translation></translation>
    </message>
    <message>
        <source>None</source>
        <translation>无</translation>
    </message>
    <message>
        <source>closing_rectangle</source>
        <translation>闭操作-矩形</translation>
    </message>
    <message>
        <source>opening_rectangle</source>
        <translation>开操作-矩形</translation>
    </message>
    <message>
        <source>closing_circle</source>
        <translation>闭操作-圆形</translation>
    </message>
    <message>
        <source>opening_circle</source>
        <translation>开操作-圆形</translation>
    </message>
    <message>
        <source>参数1：</source>
        <translation></translation>
    </message>
    <message>
        <source>参数2：</source>
        <translation></translation>
    </message>
    <message>
        <source>参数3：</source>
        <translation></translation>
    </message>
    <message>
        <source>ROI-%1</source>
        <translation></translation>
    </message>
    <message>
        <source>exit test</source>
        <translation>退出测试</translation>
    </message>
    <message>
        <source>test mode</source>
        <translation>测试模式</translation>
    </message>
</context>
</TS>
