<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>arithmetic_preWidget</name>
    <message>
        <source>arithmetic_preWidget</source>
        <translation></translation>
    </message>
    <message>
        <source>启用模块</source>
        <translation></translation>
    </message>
    <message>
        <source>输出</source>
        <translation></translation>
    </message>
    <message>
        <source>图像1</source>
        <translation></translation>
    </message>
    <message>
        <source>图像2</source>
        <translation></translation>
    </message>
    <message>
        <source>编辑</source>
        <translation></translation>
    </message>
    <message>
        <source>ROI数目</source>
        <translation></translation>
    </message>
    <message>
        <source>选择区域</source>
        <translation></translation>
    </message>
    <message>
        <source>整幅图片</source>
        <translation></translation>
    </message>
    <message>
        <source>加</source>
        <translation></translation>
    </message>
    <message>
        <source>减</source>
        <translation></translation>
    </message>
    <message>
        <source>乘</source>
        <translation></translation>
    </message>
    <message>
        <source>除</source>
        <translation></translation>
    </message>
    <message>
        <source>最大</source>
        <translation></translation>
    </message>
    <message>
        <source>最小</source>
        <translation></translation>
    </message>
    <message>
        <source>与</source>
        <translation></translation>
    </message>
    <message>
        <source>或</source>
        <translation></translation>
    </message>
    <message>
        <source>非</source>
        <translation></translation>
    </message>
    <message>
        <source>与非</source>
        <translation></translation>
    </message>
    <message>
        <source>或非</source>
        <translation></translation>
    </message>
    <message>
        <source>异或</source>
        <translation></translation>
    </message>
    <message>
        <source>异或非</source>
        <translation></translation>
    </message>
    <message>
        <source>参数a</source>
        <translation></translation>
    </message>
    <message>
        <source>参数b</source>
        <translation></translation>
    </message>
    <message>
        <source>参数c</source>
        <translation></translation>
    </message>
    <message>
        <source>ROI OK</source>
        <translation>确定</translation>
    </message>
    <message>
        <source>roi%1</source>
        <translation>区域%1</translation>
    </message>
    <message>
        <source>select ROI</source>
        <translation>选择区域</translation>
    </message>
    <message>
        <source> Check</source>
        <translation>启用</translation>
    </message>
    <message>
        <source> Unchecked</source>
        <translation>不启用</translation>
    </message>
    <message>
        <source>%1 val changed from %2 to %3</source>
        <translation>%1的值从%2改变为%3</translation>
    </message>
    <message>
        <source>first img</source>
        <translation>第一张图</translation>
    </message>
    <message>
        <source>second img</source>
        <translation>第二张图</translation>
    </message>
    <message>
        <source>operator</source>
        <translation>算子</translation>
    </message>
    <message>
        <source>output</source>
        <translation>输出图片</translation>
    </message>
</context>
</TS>
