<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>QObject</name>
    <message>
        <source>Empty image!</source>
        <translation>无图片传入！</translation>
    </message>
    <message>
        <source>Input matrix&apos;s size != 6!</source>
        <translation>输入矩阵大小不等于6！</translation>
    </message>
    <message>
        <source>base line detect failed!</source>
        <translation>基准直线识别失败！</translation>
    </message>
    <message>
        <source>%1 line detect failed!</source>
        <translation>%1管脚直线识别失败！</translation>
    </message>
    <message>
        <source>left</source>
        <translation>左</translation>
    </message>
    <message>
        <source>right</source>
        <translation>右</translation>
    </message>
    <message>
        <source>failed</source>
        <translation>失败</translation>
    </message>
    <message>
        <source>passed</source>
        <translation>通过</translation>
    </message>
    <message>
        <source>%1 line%2 &amp; base line: %3 [%4,%5] %6</source>
        <translation>%1管脚直线%2 -基准直线：%3 [%4,%5] %6</translation>
    </message>
    <message>
        <source>base</source>
        <translation>基准</translation>
    </message>
</context>
<context>
    <name>angleFilterWdg</name>
    <message>
        <source>angleFilterWdg</source>
        <translation></translation>
    </message>
    <message>
        <source>选直线</source>
        <translation></translation>
    </message>
    <message>
        <source>确定</source>
        <translation></translation>
    </message>
    <message>
        <source>取消</source>
        <translation></translation>
    </message>
    <message>
        <source>旋转矩阵</source>
        <translation></translation>
    </message>
    <message>
        <source>测后显示</source>
        <translation></translation>
    </message>
    <message>
        <source>参数选择</source>
        <translation></translation>
    </message>
    <message>
        <source>基准区域</source>
        <translation></translation>
    </message>
    <message>
        <source>左管脚正向</source>
        <translation></translation>
    </message>
    <message>
        <source>右管脚正向</source>
        <translation></translation>
    </message>
    <message>
        <source>左管脚反向</source>
        <translation></translation>
    </message>
    <message>
        <source>右管脚反向</source>
        <translation></translation>
    </message>
    <message>
        <source>所有区域使用基准区域参数</source>
        <translation></translation>
    </message>
    <message>
        <source>线属性</source>
        <translation></translation>
    </message>
    <message>
        <source>高级参数</source>
        <translation></translation>
    </message>
    <message>
        <source>最大迭代次数</source>
        <translation></translation>
    </message>
    <message>
        <source>极性</source>
        <translation></translation>
    </message>
    <message>
        <source>最大对比</source>
        <translation></translation>
    </message>
    <message>
        <source>第一条</source>
        <translation></translation>
    </message>
    <message>
        <source>双向</source>
        <translation></translation>
    </message>
    <message>
        <source>黑到白</source>
        <translation></translation>
    </message>
    <message>
        <source>白到黑</source>
        <translation></translation>
    </message>
    <message>
        <source>对比度</source>
        <translation></translation>
    </message>
    <message>
        <source>直线</source>
        <translation></translation>
    </message>
    <message>
        <source>毛边</source>
        <translation></translation>
    </message>
    <message>
        <source>角度范围</source>
        <translation></translation>
    </message>
    <message>
        <source>排除距离</source>
        <translation></translation>
    </message>
    <message>
        <source>基准区域-右管脚</source>
        <translation></translation>
    </message>
    <message>
        <source>基准区域-左管脚</source>
        <translation></translation>
    </message>
    <message>
        <source>warning</source>
        <translation>警告</translation>
    </message>
    <message>
        <source>Whether to apply the base line parameters to all regions?</source>
        <translation>是否将基准区域参数运用于其他所有区域？</translation>
    </message>
    <message>
        <source>Appling the base line parameters to all regions</source>
        <translation>所有参数同步到基准区域参数</translation>
    </message>
    <message>
        <source> Checked</source>
        <translation>启用</translation>
    </message>
    <message>
        <source> Unchecked</source>
        <translation>不启用</translation>
    </message>
    <message>
        <source> %1 val changed from %2 to %3</source>
        <translation>%1的值从%2改变为%3</translation>
    </message>
    <message>
        <source>%1 max val changed from %2 to %3</source>
        <translation>%1的最大值从%2变为%3</translation>
    </message>
    <message>
        <source>%1 min val changed from %2 to %3</source>
        <translation>%1的最小值从%2变为%3</translation>
    </message>
    <message>
        <source>base</source>
        <translation>基准</translation>
    </message>
    <message>
        <source>left</source>
        <translation>左</translation>
    </message>
    <message>
        <source>right</source>
        <translation>右</translation>
    </message>
</context>
</TS>
