<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>QObject</name>
    <message>
        <source>Empty image!</source>
        <translation>无图片传入</translation>
    </message>
    <message>
        <source>Input matrix&apos;s size !=6</source>
        <translation>旋转矩阵大小不为6！</translation>
    </message>
    <message>
        <source>lead %1 found failed</source>
        <translation>管脚%1寻找失败</translation>
    </message>
    <message>
        <source>Lead%1:</source>
        <translation>管脚%1：</translation>
    </message>
    <message>
        <source> Width:%1(%2,%3)</source>
        <translation>宽度：%1(%2,%3)</translation>
    </message>
    <message>
        <source> Length:%1(%2,%3)</source>
        <translation>长度:%1(%2,%3)</translation>
    </message>
    <message>
        <source> Interval:%1(%2,%3)</source>
        <translation>间距：%1(%2,%3)</translation>
    </message>
</context>
<context>
    <name>segLeadWdg</name>
    <message>
        <source>segLeadWdg</source>
        <translation></translation>
    </message>
    <message>
        <source>属性</source>
        <translation></translation>
    </message>
    <message>
        <source>检测区域</source>
        <translation></translation>
    </message>
    <message>
        <source>区域选取</source>
        <translation></translation>
    </message>
    <message>
        <source>旋转矩阵参考</source>
        <translation></translation>
    </message>
    <message>
        <source>用于传入在计算管脚长宽时的基准线</source>
        <translation></translation>
    </message>
    <message>
        <source>传入边界参考</source>
        <translation></translation>
    </message>
    <message>
        <source>传入比例</source>
        <translation></translation>
    </message>
    <message>
        <source>mm</source>
        <translation></translation>
    </message>
    <message>
        <source>比例尺</source>
        <translation></translation>
    </message>
    <message>
        <source>测后显示</source>
        <translation></translation>
    </message>
    <message>
        <source>测试模式</source>
        <translation></translation>
    </message>
    <message>
        <source>管脚面积：</source>
        <translation></translation>
    </message>
    <message>
        <source>管脚数目：</source>
        <translation></translation>
    </message>
    <message>
        <source>开操作：</source>
        <translation></translation>
    </message>
    <message>
        <source>宽度</source>
        <translation></translation>
    </message>
    <message>
        <source>高度</source>
        <translation></translation>
    </message>
    <message>
        <source>闭操作：</source>
        <translation></translation>
    </message>
    <message>
        <source>管脚朝向：</source>
        <translation></translation>
    </message>
    <message>
        <source>横向管脚</source>
        <translation></translation>
    </message>
    <message>
        <source>纵向管脚</source>
        <translation></translation>
    </message>
    <message>
        <source>自动分割</source>
        <translation></translation>
    </message>
    <message>
        <source>检测方法：</source>
        <translation></translation>
    </message>
    <message>
        <source>平滑背景</source>
        <translation></translation>
    </message>
    <message>
        <source>连续区域</source>
        <translation></translation>
    </message>
    <message>
        <source>固定阈值</source>
        <translation></translation>
    </message>
    <message>
        <source>白色目标</source>
        <translation></translation>
    </message>
    <message>
        <source>黑色目标</source>
        <translation></translation>
    </message>
    <message>
        <source>平滑尺寸：</source>
        <translation></translation>
    </message>
    <message>
        <source>灰度差值：</source>
        <translation></translation>
    </message>
    <message>
        <source>目标类型：</source>
        <translation></translation>
    </message>
    <message>
        <source>白色</source>
        <translation></translation>
    </message>
    <message>
        <source>黑色</source>
        <translation></translation>
    </message>
    <message>
        <source>以ROI中心为种子点</source>
        <translation></translation>
    </message>
    <message>
        <source>设置种子点</source>
        <translation></translation>
    </message>
    <message>
        <source>x:</source>
        <translation></translation>
    </message>
    <message>
        <source>y:</source>
        <translation></translation>
    </message>
    <message>
        <source>行距离</source>
        <translation></translation>
    </message>
    <message>
        <source>最小面积</source>
        <translation></translation>
    </message>
    <message>
        <source>列距离</source>
        <translation></translation>
    </message>
    <message>
        <source>灰度差距</source>
        <translation></translation>
    </message>
    <message>
        <source>阈值范围：</source>
        <translation></translation>
    </message>
    <message>
        <source>自动分割阈值：</source>
        <translation></translation>
    </message>
    <message>
        <source> 管脚区域尺寸</source>
        <translation></translation>
    </message>
    <message>
        <source>白色管脚</source>
        <translation></translation>
    </message>
    <message>
        <source>黑色管脚</source>
        <translation></translation>
    </message>
    <message>
        <source>误差范围</source>
        <translation></translation>
    </message>
    <message>
        <source>管脚宽度</source>
        <translation></translation>
    </message>
    <message>
        <source>管脚长度</source>
        <translation></translation>
    </message>
    <message>
        <source>管脚间距</source>
        <translation></translation>
    </message>
    <message>
        <source>到边距离</source>
        <translation></translation>
    </message>
    <message>
        <source>管脚1</source>
        <translation></translation>
    </message>
    <message>
        <source>全使用脚1数据</source>
        <translation></translation>
    </message>
    <message>
        <source>lead%1</source>
        <translation>管脚%1</translation>
    </message>
    <message>
        <source>SearchRoi</source>
        <translation>搜寻区域</translation>
    </message>
    <message>
        <source> Check</source>
        <translation>启用</translation>
    </message>
    <message>
        <source> Uncheck</source>
        <translation>不启用</translation>
    </message>
    <message>
        <source> min val</source>
        <translation>最小值</translation>
    </message>
    <message>
        <source> change from %1 to %2</source>
        <translation>从%1改变为%2</translation>
    </message>
    <message>
        <source> max val</source>
        <translation>最大值</translation>
    </message>
    <message>
        <source>ROI OK</source>
        <translation>确认</translation>
    </message>
    <message>
        <source>Sel ROI</source>
        <translation>选择区域</translation>
    </message>
    <message>
        <source>Warning!</source>
        <translation>警告！</translation>
    </message>
    <message>
        <source>make sure to set all leads&apos; param the same as lead 1?</source>
        <translation>是否将管脚1参数同步到所有管脚？</translation>
    </message>
    <message>
        <source>exit seg</source>
        <translation>退出分割</translation>
    </message>
    <message>
        <source>auto seg</source>
        <translation>自动分割</translation>
    </message>
</context>
</TS>
