<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>GRRreportWdg</name>
    <message>
        <source>GRRreportWdg</source>
        <translation></translation>
    </message>
    <message>
        <source>模块数：</source>
        <translation></translation>
    </message>
    <message>
        <source>报告模式：</source>
        <translation></translation>
    </message>
    <message>
        <source>SPC</source>
        <translation></translation>
    </message>
    <message>
        <source>使用标准公差</source>
        <translation></translation>
    </message>
    <message>
        <source>单元数：</source>
        <translation></translation>
    </message>
    <message>
        <source>输出详细数据</source>
        <translation></translation>
    </message>
    <message>
        <source>批次名：</source>
        <translation></translation>
    </message>
    <message>
        <source>检测数目：</source>
        <translation></translation>
    </message>
    <message>
        <source>0/30</source>
        <translation></translation>
    </message>
    <message>
        <source>记录状态：</source>
        <translation></translation>
    </message>
    <message>
        <source>complete</source>
        <translation></translation>
    </message>
    <message>
        <source>准备</source>
        <translation></translation>
    </message>
    <message>
        <source>导出报告</source>
        <translation></translation>
    </message>
    <message>
        <source>information</source>
        <translation>提示</translation>
    </message>
    <message>
        <source>The default output is a csv file. Should it be changed to an html file (read-only)?</source>
        <translation>默认输出格式为.csv，是否修改为只读格式.html？</translation>
    </message>
    <message>
        <source>Set Text</source>
        <translation></translation>
    </message>
    <message>
        <source>Text:</source>
        <translation></translation>
    </message>
    <message>
        <source>Item</source>
        <translation>项目</translation>
    </message>
    <message>
        <source>Enable</source>
        <translation>可用</translation>
    </message>
    <message>
        <source>Text</source>
        <translation>文本</translation>
    </message>
    <message>
        <source>LSL</source>
        <translation></translation>
    </message>
    <message>
        <source>USL</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>QObject</name>
    <message>
        <source>GRR data error: Module detection is failed! Please restart GRR again!</source>
        <translation>GRR数据错误：前置模块识别失败！请重新执行GRR！</translation>
    </message>
    <message>
        <source>GRR data error: The unit&apos;s size of data is not equal to the No.1! Please restart GRR again!</source>
        <translation>GRR数据错误：该料的数据长度异常！请重新执行GRR！</translation>
    </message>
    <message>
        <source>Count: %1/%2</source>
        <translation>数目：%1/%2</translation>
    </message>
    <message>
        <source>information</source>
        <translation>提示</translation>
    </message>
    <message>
        <source>The default output is a csv file. Should it be changed to an html file (read-only)?</source>
        <translation>默认输出格式为.csv，是否修改为只读格式.html？</translation>
    </message>
</context>
</TS>
