<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="zh_CN">
<context>
    <name>QObject</name>
    <message>
        <source>Empty image!</source>
        <translation>无图片传入！</translation>
    </message>
    <message>
        <source>Need to input a 2*3 matrix!</source>
        <translation>需要传入一个2*3矩阵！</translation>
    </message>
    <message>
        <source>Detect failed!</source>
        <translation>识别失败！</translation>
    </message>
    <message>
        <source>no object found</source>
        <translation>无物体发现</translation>
    </message>
    <message>
        <source>area count: %1(%2,%3)</source>
        <translation>区域数目: %1(%2,%3)</translation>
    </message>
    <message>
        <source>max single area: %1(%2,%3)</source>
        <translation>最大单个区域面积: %1(%2,%3)</translation>
    </message>
    <message>
        <source> length%1: %2(%3,%4)</source>
        <translation> 长度%1: %2(%3,%4)</translation>
    </message>
    <message>
        <source> width%1: %2(%3,%4)</source>
        <translation> 宽度%1: %2(%3,%4)</translation>
    </message>
    <message>
        <source> total bad area: %1(%2,%3)</source>
        <translation> 总面积: %1(%2,%3)</translation>
    </message>
</context>
<context>
    <name>surfacePAdvanceDialog</name>
    <message>
        <source>surfacePAdvanceDialog</source>
        <translation></translation>
    </message>
    <message>
        <source>传入区域调整</source>
        <translation></translation>
    </message>
    <message>
        <source>右</source>
        <translation></translation>
    </message>
    <message>
        <source>面区域缩放:</source>
        <translation></translation>
    </message>
    <message>
        <source>点区域缩放：</source>
        <translation></translation>
    </message>
    <message>
        <source>上</source>
        <translation></translation>
    </message>
    <message>
        <source>下</source>
        <translation></translation>
    </message>
    <message>
        <source>左</source>
        <translation></translation>
    </message>
    <message>
        <source>点区域圆角:</source>
        <translation></translation>
    </message>
    <message>
        <source>排除区域</source>
        <translation></translation>
    </message>
    <message>
        <source>排除模组：</source>
        <translation></translation>
    </message>
    <message>
        <source>排除2：  </source>
        <translation></translation>
    </message>
    <message>
        <source>胀缩：</source>
        <translation></translation>
    </message>
    <message>
        <source>排除1：  </source>
        <translation></translation>
    </message>
    <message>
        <source>排除3：  </source>
        <translation></translation>
    </message>
    <message>
        <source>测后显示：</source>
        <translation></translation>
    </message>
    <message>
        <source>增加排除区域：</source>
        <translation></translation>
    </message>
    <message>
        <source>将前方传入点/面区域引用为排除区域</source>
        <translation></translation>
    </message>
    <message>
        <source>引用传入点区域为排除区域:</source>
        <translation></translation>
    </message>
    <message>
        <source>比例尺</source>
        <translation></translation>
    </message>
    <message>
        <source>像素尺寸</source>
        <translation></translation>
    </message>
    <message>
        <source>实际尺寸</source>
        <translation></translation>
    </message>
    <message>
        <source>mm</source>
        <translation></translation>
    </message>
    <message>
        <source>获取比例尺</source>
        <translation></translation>
    </message>
    <message>
        <source>确认</source>
        <translation></translation>
    </message>
</context>
<context>
    <name>surface_pWdg</name>
    <message>
        <source>surface_pWdg</source>
        <translation></translation>
    </message>
    <message>
        <source>属性</source>
        <translation></translation>
    </message>
    <message>
        <source>检测区域</source>
        <translation></translation>
    </message>
    <message>
        <source>区域选取</source>
        <translation></translation>
    </message>
    <message>
        <source>参考模组：</source>
        <translation></translation>
    </message>
    <message>
        <source>矩形</source>
        <translation></translation>
    </message>
    <message>
        <source>圆形</source>
        <translation></translation>
    </message>
    <message>
        <source>传入点区域</source>
        <translation></translation>
    </message>
    <message>
        <source>传入面区域</source>
        <translation></translation>
    </message>
    <message>
        <source>绘制区域</source>
        <translation></translation>
    </message>
    <message>
        <source>旋转矩阵参考</source>
        <translation></translation>
    </message>
    <message>
        <source>阈值处理</source>
        <translation></translation>
    </message>
    <message>
        <source>min</source>
        <translation></translation>
    </message>
    <message>
        <source>max</source>
        <translation></translation>
    </message>
    <message>
        <source>面积：</source>
        <translation></translation>
    </message>
    <message>
        <source>高级设置</source>
        <translation></translation>
    </message>
    <message>
        <source>测后显示</source>
        <translation></translation>
    </message>
    <message>
        <source>测试模式</source>
        <translation></translation>
    </message>
    <message>
        <source>瑕疵定义</source>
        <translation></translation>
    </message>
    <message>
        <source>原图滤波</source>
        <translation></translation>
    </message>
    <message>
        <source>开操作：</source>
        <translation></translation>
    </message>
    <message>
        <source>高度：</source>
        <translation></translation>
    </message>
    <message>
        <source>宽度：</source>
        <translation></translation>
    </message>
    <message>
        <source>闭操作：</source>
        <translation></translation>
    </message>
    <message>
        <source>平均背景</source>
        <translation></translation>
    </message>
    <message>
        <source>固定阈值</source>
        <translation></translation>
    </message>
    <message>
        <source>平滑背景</source>
        <translation></translation>
    </message>
    <message>
        <source>检测孔洞</source>
        <translation></translation>
    </message>
    <message>
        <source>毛刺缺失</source>
        <translation></translation>
    </message>
    <message>
        <source>白色缺陷：</source>
        <translation></translation>
    </message>
    <message>
        <source>黑色缺陷：</source>
        <translation></translation>
    </message>
    <message>
        <source>阈值范围：</source>
        <translation></translation>
    </message>
    <message>
        <source>平滑尺寸：</source>
        <translation></translation>
    </message>
    <message>
        <source>将ROI外的区域填充为某一灰度值</source>
        <translation></translation>
    </message>
    <message>
        <source>填充ROI外</source>
        <translation></translation>
    </message>
    <message>
        <source>孔面积:</source>
        <translation></translation>
    </message>
    <message>
        <source>孔数目:</source>
        <translation></translation>
    </message>
    <message>
        <source>最小毛刺:</source>
        <translation></translation>
    </message>
    <message>
        <source>最小缺失:</source>
        <translation></translation>
    </message>
    <message>
        <source>最小面积:</source>
        <translation></translation>
    </message>
    <message>
        <source>拟合完整矩形</source>
        <translation></translation>
    </message>
    <message>
        <source>误差范围</source>
        <translation></translation>
    </message>
    <message>
        <source>宽度：       </source>
        <translation></translation>
    </message>
    <message>
        <source>长度：       </source>
        <translation></translation>
    </message>
    <message>
        <source>缺陷总面积： </source>
        <translation></translation>
    </message>
    <message>
        <source>单个缺陷面积：</source>
        <translation></translation>
    </message>
    <message>
        <source>数目       ：</source>
        <translation></translation>
    </message>
    <message>
        <source> change from %1 to %2</source>
        <translation>从%1改变为%2</translation>
    </message>
    <message>
        <source> min val </source>
        <translation>最小值</translation>
    </message>
    <message>
        <source> max val </source>
        <translation>最大值</translation>
    </message>
    <message>
        <source>ROI OK</source>
        <translation>确认区域</translation>
    </message>
    <message>
        <source>select type</source>
        <translation>选择类型</translation>
    </message>
    <message>
        <source>select circular ROI?</source>
        <translation>是否选择圆形ROI？</translation>
    </message>
    <message>
        <source>Select ROI</source>
        <translation>选择区域</translation>
    </message>
    <message>
        <source>exit test</source>
        <translation>退出测试</translation>
    </message>
    <message>
        <source>test</source>
        <translation>测试模式</translation>
    </message>
    <message>
        <source> Check</source>
        <translation>启用</translation>
    </message>
    <message>
        <source> unCheck</source>
        <translation>不启用</translation>
    </message>
</context>
</TS>
